# Generated by Django 5.0.4 on 2024-04-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_owner_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profiles/images/default.png', upload_to='profiles/'),
        ),
    ]
