# Generated by Django 5.0.4 on 2024-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
    ]
