# Generated by Django 5.0.4 on 2024-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
