# Generated by Django 5.0.4 on 2024-05-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0015_remove_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField()),
                ('theme_dinner', models.CharField(blank=True, max_length=100)),
                ('allergies', models.CharField(blank=True, max_length=500)),
                ('type_of_dinner', models.CharField(blank=True, max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='profiles.profile')),
                ('invited_profiles', models.ManyToManyField(related_name='invited_events', to='profiles.profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_events', to='profiles.profile')),
            ],
        ),
    ]
