# Generated by Django 5.0.4 on 2024-05-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_follower_unique_together'),
        ('profiles', '0015_remove_profile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('profile', 'follower')},
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='profiles.profile', verbose_name='Follower'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='profiles.profile', verbose_name='Profile'),
        ),
    ]
