# Generated by Django 5.0.4 on 2024-05-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_alter_follower_options_and_more'),
        ('profiles', '0015_remove_profile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={},
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile'),
        ),
    ]
