# Generated by Django 5.0.4 on 2024-05-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_alter_follower_options_alter_follower_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at']},
        ),
    ]
